#!/usr/bin/env python3
"""Generate the puddle shapes -- the pack's organic content field, for the web.

Every FLIPO's pouch puts its content inside a wobbly white puddle sitting on a
doodle ground. The site currently uses rounded rectangles everywhere, which is
the single biggest reason it does not look like the packaging. These are the
puddle, as reusable clip paths.

Emitted in objectBoundingBox units (0..1) rather than as fixed-size SVG paths,
so ONE shape stretches to any element -- a wide panel, a tall card, a square
image -- via `clip-path: url(#id)`. No per-size regeneration, no wrapper SVG in
the markup, and it clips images as happily as it clips divs.

Shapes are a squircle base with a few harmonics of wobble on top:

    r(t) = squircle(t, n) * (1 + SUM a_k cos(k*t + phase_k))

`n` sets squareness -- low is a soft blob, high is nearly a rounded rectangle --
and the harmonics do the hand-drawn irregularity. Each shape is then normalised
to fill its box exactly, so a clipped element loses no width or height.

Run `python tools/build-blobs.py` from the repo root. Outputs:
  src/components/ui/BlobShapes.jsx
"""

import math
import os

# Deliberately few, deliberately varied. Repeating one puddle across a grid
# reads as a stamp; three per role is enough to break the pattern without
# turning into noise.
#   name        n     amplitude  harmonics       seed
SHAPES = [
    ("card1", 3.6, 0.030, (3, 5, 7), 11),
    ("card2", 3.4, 0.036, (3, 4, 7), 29),
    ("card3", 3.8, 0.026, (2, 5, 8), 47),
    ("puddle1", 2.6, 0.052, (3, 5, 6), 5),
    ("puddle2", 2.4, 0.060, (2, 4, 7), 71),
    ("stamp1", 2.9, 0.044, (3, 6, 8), 97),
    # Wide bands stretch the wobble horizontally, which turns a lively edge into
    # a lumpy one. These trade amplitude for squareness so they hold at 7:2+.
    ("wide1", 4.6, 0.015, (4, 6, 9), 13),
    ("wide2", 4.4, 0.018, (3, 7, 9), 59),
]
SAMPLES = 44


def lcg(seed):
    """Small deterministic PRNG -- the shapes must not move between builds."""
    state = seed * 1103515245 + 12345
    while True:
        state = (state * 1103515245 + 12345) % (1 << 31)
        yield state / float(1 << 31)


def squircle(theta, n):
    c, s = abs(math.cos(theta)), abs(math.sin(theta))
    return 1.0 / ((c ** n + s ** n) ** (1.0 / n))


def build(n, amp, harmonics, seed):
    rnd = lcg(seed)
    phases = [next(rnd) * 2 * math.pi for _ in harmonics]
    weights = [0.6 + 0.4 * next(rnd) for _ in harmonics]
    total = sum(weights)
    pts = []
    for i in range(SAMPLES):
        t = 2 * math.pi * i / SAMPLES
        wobble = sum(
            (w / total) * math.cos(k * t + p)
            for k, p, w in zip(harmonics, phases, weights)
        )
        r = squircle(t, n) * (1.0 + amp * wobble * 3.0)
        pts.append((r * math.cos(t), r * math.sin(t)))

    # Normalise to fill the unit box exactly, so a clipped element keeps its
    # full width and height.
    xs = [p[0] for p in pts]
    ys = [p[1] for p in pts]
    x0, x1 = min(xs), max(xs)
    y0, y1 = min(ys), max(ys)
    return [((x - x0) / (x1 - x0), (y - y0) / (y1 - y0)) for x, y in pts]


def smooth_closed(pts, prec=4):
    """Closed Catmull-Rom through pts as cubic beziers."""
    n = len(pts)
    f = "%%.%df" % prec
    out = [("M" + f + "," + f) % pts[0]]
    for i in range(n):
        p0, p1 = pts[(i - 1) % n], pts[i]
        p2, p3 = pts[(i + 1) % n], pts[(i + 2) % n]
        c1 = (p1[0] + (p2[0] - p0[0]) / 6.0, p1[1] + (p2[1] - p0[1]) / 6.0)
        c2 = (p2[0] - (p3[0] - p1[0]) / 6.0, p2[1] - (p3[1] - p1[1]) / 6.0)
        out.append(("C" + ",".join([f] * 6)) % (c1[0], c1[1], c2[0], c2[1], p2[0], p2[1]))
    return " ".join(out) + "Z"


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    paths = [(name, smooth_closed(build(n, amp, h, seed)))
             for name, n, amp, h, seed in SHAPES]

    body = [
        "// The pack's organic content puddle, as reusable clip paths.",
        "// Generated by tools/build-blobs.py -- edit the generator, not this file.",
        "//",
        "// Coordinates are objectBoundingBox units (0..1), so one shape stretches to",
        "// any element and clips images as readily as divs. Mount <BlobClipDefs/> once",
        "// near the app root, then clip anything with blobClip('card1').",
        "//",
        "// Note: `Blob` in ./Primitives.jsx is the small scattered accent doodle --",
        "// unrelated to these container shapes.",
        "",
        "export const BLOB_PATHS = {",
    ]
    for name, d in paths:
        body.append("  %s: '%s'," % (name, d))
    body.append("}\n")
    body.append("export const BLOB_NAMES = Object.keys(BLOB_PATHS)\n")
    body.append("/** Pick a shape deterministically, so a given card always gets the same one. */")
    body.append("export function blobShape(index, role = 'card') {")
    body.append("  const pool = BLOB_NAMES.filter((n) => n.startsWith(role))")
    body.append("  const names = pool.length ? pool : BLOB_NAMES")
    body.append("  return names[((index % names.length) + names.length) % names.length]")
    body.append("}\n")
    body.append("/** Style object clipping an element to one of the shapes. */")
    body.append("export function blobClip(name) {")
    body.append("  return { clipPath: `url(#jni-blob-${name})` }")
    body.append("}\n")
    body.append("/** Mount once. Renders the clipPath defs every blobClip() refers to. */")
    body.append("export function BlobClipDefs() {")
    body.append("  return (")
    body.append("    <svg width=\"0\" height=\"0\" aria-hidden=\"true\"")
    body.append("      style={{ position: 'absolute', width: 0, height: 0, overflow: 'hidden' }}>")
    body.append("      <defs>")
    body.append("        {BLOB_NAMES.map((name) => (")
    body.append("          <clipPath key={name} id={`jni-blob-${name}`} clipPathUnits=\"objectBoundingBox\">")
    body.append("            <path d={BLOB_PATHS[name]} />")
    body.append("          </clipPath>")
    body.append("        ))}")
    body.append("      </defs>")
    body.append("    </svg>")
    body.append("  )")
    body.append("}")

    out = os.path.join(root, "src", "components", "ui", "BlobShapes.jsx")
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(body) + "\n")
    print("%d shapes -> src/components/ui/BlobShapes.jsx" % len(paths))
    for name, d in paths:
        print("  %-8s %d chars" % (name, len(d)))


if __name__ == "__main__":
    main()
